# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-c60ed754-e327-4e2e-bb9f-2bb90f46fa27";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-c60ed754-e327-4e2e-bb9f-2bb90f46fa27".device = "/dev/disk/by-uuid/c60ed754-e327-4e2e-bb9f-2bb90f46fa27";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0745-577D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [mangohud];
    extraPackages32 = with pkgs; [mangohud];
  };

  hardware.bluetooth.enable = true; # enables the bluez service
  hardware.bluetooth.powerOnBoot = true; # powers up the default controller on boot
  services.blueman.enable = true; # provides the GUI and tray applet

  services.xserver.videoDrivers = ["amdgpu"];

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/1892489E9248826C";
    fsType = "ntfs3";
    options = [
      "nofail"
      "uid=1000"
      "gid=100"
      "rw"
      "user"
      "exec" # Explicitly allow executing binaries (critical for Steam)
      "umask=000" # Simplest way to give full access; or use dmask=000,fmask=000
      "windows_names" # Prevents creating files with names Windows doesn't like
    ];
  };
}
