# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  # smb mount opts variable
  smbOptions = [
    "credentials=/home/kusha/nixos-config/secrets/netdisk-secret"
    "uid=1000"
    "gid=100"
    "rw"
    "vers=3.0"
    "x-systemd.automount" # This makes it "lazy load" like Windows
    "noauto"
    "x-systemd.idle-timeout=60" # Unmounts when not in use to save resources
  ];
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-c60ed754-e327-4e2e-bb9f-2bb90f46fa27";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-c60ed754-e327-4e2e-bb9f-2bb90f46fa27".device = "/dev/disk/by-uuid/c60ed754-e327-4e2e-bb9f-2bb90f46fa27";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0745-577D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [mangohud];
    extraPackages32 = with pkgs; [mangohud];
  };

  hardware.bluetooth.enable = true; # enables the bluez service
  hardware.bluetooth.powerOnBoot = false; # powers up the default controller on boot
  services.blueman.enable = true; # provides the GUI and tray applet

  # resolve home lab stuff with local DNS
  services.resolved = {
    enable = true;
    extraConfig = ''
      [Resolve]
      DNS=192.168.1.241
      Domains=kusha.me
    '';
  };
  # Mount homelab smb
  fileSystems."/mnt/netdisk/home" = {
    device = "//192.168.1.23/home";
    fsType = "cifs";
    options = smbOptions;
  };

  fileSystems."/mnt/netdisk/media" = {
    device = "//192.168.1.23/Media";
    fsType = "cifs";
    options = smbOptions;
  };

  fileSystems."/mnt/netdisk/docker" = {
    device = "//192.168.1.23/docker";
    fsType = "cifs";
    options = smbOptions;
  };

  fileSystems."/mnt/netdisk/photos" = {
    device = "//192.168.1.23/photo-frame";
    fsType = "cifs";
    options = smbOptions;
  };

  # brlaser is the most reliable modern driver for Brother HL-2070N series
  services.printing.drivers = [pkgs.brlaser];

  hardware.printers = {
    ensurePrinters = [
      {
        name = "Brother_HL-2070N";
        location = "Local Printer";
        # Use 'socket' for the most reliable connection
        deviceUri = "socket://192.168.1.56:9100";
        model = "drv:///brlaser.drv/br2140.ppd";
        description = "Brother HL-2070N (Static IP)";
      }
    ];
  };

  services.xserver.videoDrivers = ["amdgpu"];

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/1892489E9248826C";
    fsType = "ntfs3";
    options = [
      "nofail"
      "uid=1000"
      "gid=100"
      "rw"
      "user"
      "exec" # Explicitly allow executing binaries (critical for Steam)
      "umask=000" # Simplest way to give full access; or use dmask=000,fmask=000
      #"windows_names" # Prevents creating files with names Windows doesn't like
    ];
  };
}
